export const imgProd = require('./prod.png')
export const imgCheque = require('./cheque.png')
export const imgFrame = require('./Frame.png')
export const imgIllustration = require('./Illustration.png')
export const imgLayer = require('./_Layer_.png')
export const imgCampo = require('./campo.png')
export const imgProductorGif = require('./productorGif.gif')
