export const LABELS = {
  createAccount: 'Crea tu cuenta personal',
  initial: 'INICIAR',
  email: 'Correo electrónico',
  registerDni: 'Escribe tu DNI',
  dni: 'DNI',
  phoneRegister: 'Escribe tu número de celular',
  nameParcel: '¿NOMBRE DE TU PARCELA?',
  hectaresParcel: '¿NÚMERO DE HECTÁREAS?',
  nameRegister: 'Escribe tu nombre completo',
  next: 'SIGUIENTE',
  imAlreadyEntrance: 'ESTOY EN LA ENTRADA',
  capturePhoto: 'TOMAR FOTOGRAFÍA',
  imAlreadyCenter: 'ESTOY EN EL CENTRO',
  confirm: 'Confirmar',
  saveGps: 'GUARDAR UBICACIÓN',
  addParcel: 'REGISTRAR PARCELA',
  password: 'Contraseña',
  rePassword: 'Repite tu contraseña',
  pin: 'Crea tu PIN de seguridad',
  rePin: 'Repite tu PIN',
  name: 'Nombre',
  namePersonal: 'Escribe tu nombre completo',
  phonePersonal: 'Escribe tu número de celular',
  phone: 'Teléfono',
  error: 'Error',
  cancel: 'Cancelar',
  AskMeLater: 'Pregúntame Luego',
  permission: 'Permitir',
  continue: 'CONTINUAR',
  offline: 'DESCONECTADO',
  online: 'CONECTADO',
  offlineMessage: '(No tienes conexión a internet)',
  asyncData: 'Guardar datos',
  myEntrance: 'Mi entrada',
  viewMyParcels: 'Ver mis parcelas',
  registerCosecha: 'Registrar cosecha',
  registerVenta: 'Registrar una venta',
  requestPermissionLocation: 'PERMISO DE UBICACIÓN',
  requestPermissionCamera: 'PERMISO DE CÁMARA',
}

export const PLACEHOLDERS = {
  phone: '000-000-0000',
}
