export const LABELS = {
  createAccount: 'Crea tu cuenta personal',
  email: 'Correo electrónico',
  registerDni: 'Escribe tu DNI',
  dni: 'DNI',
  phoneRegister: 'Escribe tu número de celular',
  nameParcel: '¿NOMBRE DE TU PARCELA?',
  hectaresParcel: '¿NÚMERO DE HECTÁREAS?',
  nameRegister: 'Escribe tu nombre completo',
  next: 'SIGUIENTE',
  imAlreadyEntrance: 'ESTOY EN LA ENTRADA',
  imAlreadyCenter: 'ESTOY EN EL CENTRO',
  confirm: 'Confirmar',
  saveGps: 'GUARDAR UBICACIÓN',
  addParcel: 'REGISTRAR PARCELA',
  password: 'Contraseña',
  rePassword: 'Repite tu contraseña',
  pin: 'Crea tu PIN de seguridad',
  rePin: 'Repite tu PIN',
  name: 'Nombre',
  namePersonal: 'Escribe tu nombre completo',
  phonePersonal: 'Escribe tu número de celular',
  phone: 'Teléfono',
  error: 'Error',
  continue: 'CONTINUAR',
  offline: 'Offline',
  online: 'Online',
  offlineMessage: '(No tienes conexión a internet)',
  asyncData: 'Sincronizar datos',
  myEntrance: 'Mi entrada',
  viewMyParcels: 'Ver mis parcelas',
  registerCosecha: 'Registrar cosecha',
  registerVenta: 'Registrar una venta',
}

export const PLACEHOLDERS = {
  phone: '000-000-0000',
}
