export const LABELS = {
  createAccount: 'Crea tu cuenta personal',
  email: 'Correo electrónico',
  registerDni: 'Escribe tu DNI',
  dni: 'DNI',
  phoneRegister: 'Escribe tu número de celular',
  nameParcel: '¿Cómo se llama tu parcela?',
  nameRegister: 'Escribe tu nombre completo',
  next: 'Siguiente',
  confirm: 'Confirmar',
  addParcel: 'Registrar mi parcela',
  password: 'Contraseña',
  rePassword: 'Repite tu contraseña',
  pin: 'Crea tu PIN de seguridad',
  rePin: 'Repite tu PIN',
  name: 'Nombre',
  namePersonal: 'Escribe tu nombre completo',
  phonePersonal: 'Escribe tu número de celular',
  phone: 'Teléfono',
  error: 'Error',
  continue: 'Continuar',
  offline: 'Offline',
  online: 'Online',
  offlineMessage: '(No tienes conexión a internet)',
  asyncData: 'Sincronizar datos',
  viewMyParcels: 'Ver mis parcelas',
  registerCosecha: 'Registrar cosecha',
  registerVenta: 'Registrar una venta',
}

export const PLACEHOLDERS = {
  phone: '000-000-0000',
}
